name: Run tests on any Push event

on:
  push:
    tags:
      - "!refs/tags/*"
    branches:
      - "*"
  pull_request:
    tags:
      - "!refs/tags/*"
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          pip install poetry
          poetry shell && poetry install
      - name: Run ruff
        run: ruff src/ tests/
      - name: Run mypy
        run: mypy .