name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будут тестироваться перед сборкой.
on:
  push:
    tags:
      - "!refs/tags/*"
    branches:
      - "*"
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install poetry
        run: apt install python3-poetry
      - name: Install requirements
        run: apt install python3-poetry
      - name: Run tests
        run: coverage run src/tests.py
      - name: Tests report
        run: coverage report
